version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./public:/var/www/public:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - app

  app:
    build: ./docker
    volumes:
      - .:/var/www:cached
      - ~/.composer:/root/.composer:cached
    restart: always
    links:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql:cached
    ports:
      - "33060:3306"

  redis:
    image: redis:alpine
    volumes:
      - ./docker/storage/redis:/data:cached
    ports:
      - "63790:6379"
    restart: always

#  cron:
#    build: ./docker
#    command: cron -f
#    volumes:
#      - .:/var/www:cached
#    restart: always
#    links:
#      - mysql
#      - redis

#  worker:
#    build: ./docker
#    command: /usr/bin/supervisord
#    volumes:
#     - .:/var/www:cached
#    restart: always
#    links:
#      - mysql
#      - redis

#  horizon:
#    build: ./docker
#    command: php artisan horizon
#    volumes:
#      - .:/var/www:cached
#    restart: always
#    links:
#      - mysql
#      - redis

#  websockets:
#    build: ./docker
#    command: php artisan websockets:serve
#    volumes:
#      - .:/var/www:cached
#    restart: always
#    ports:
#      - "6001:6001"
#    links:
#      - mysql
#      - redis

#  https-portal:
#    image: steveltn/https-portal:1
#    ports:
#      - '443:443'
#    links:
#      - nginx
#    environment:
#      DOMAINS: 'docker-laravel-dev.test -> http://nginx:80'
#      STAGE: 'local'
#    volumes:
#      - ./docker/nginx/ssl:/var/lib/https-portal/
#    restart: always
