version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - app

  app:
    build: ./docker
    volumes:
      - .:/var/www
      - ~/.composer:/root/.composer
    restart: always
    links:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql
    ports:
      - "33060:3306"

  redis:
    image: redis:alpine
    volumes:
      - ./docker/storage/redis:/data
    ports:
      - "63790:6379"
    restart: always

#  cron:
#    build: ./docker
#    command: cron -f
#    volumes:
#      - .:/var/www
#    restart: always
#    links:
#      - mysql
#      - redis

#  worker:
#    build: ./docker
#    command: /usr/bin/supervisord
#    volumes:
#     - .:/var/www
#    restart: always
#    links:
#      - mysql
#      - redis

#  horizon:
#    build: ./docker
#    command: php artisan horizon
#    volumes:
#      - .:/var/www
#    restart: always
#    links:
#      - mysql
#      - redis

#  websockets:
#    build: ./docker
#    command: php artisan websockets:serve
#    volumes:
#      - .:/var/www
#    restart: always
#    ports:
#      - "6001:6001"
#    links:
#      - mysql
#      - redis
